variables:
  VERSION: "1.20.8"
  PATCH: "-1"
  IMAGE: registry.gosr.se/kube-client
  DOCKERHUB_IMAGE: mrnr91/kube-client
  DOCKER_CLI_EXPERIMENTAL: enabled
  PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
build:
  image: registry.gosr.se/norrsken/docker-builder:20
  services:
    - docker:20-dind
  stage: build
  tags:
    - buildpc
  script:
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME"  --password-stdin docker.io
    - >
      docker buildx build
      --progress plain --platform ${PLATFORMS} --push
      --cache-from $CACHE_REGISTRY_HOST/$CI_PROJECT_PATH --cache-to $CACHE_REGISTRY_HOST/$CI_PROJECT_PATH 
      -t "$IMAGE:$VERSION$PATCH" 
      -t "$IMAGE:helmsman" 
      -t "$IMAGE:latest" 
      -t "$DOCKERHUB_IMAGE:$VERSION$PATCH" 
      -t "$DOCKERHUB_IMAGE:helmsman" 
      -t "$DOCKERHUB_IMAGE:latest" 
      .
